package football

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"strconv"
	"time"

	"github.com/Gibson990/Raphbet/backend/internal/domain"
)

// APISportsProvider talks to api-football v3 (api-sports.io). It only fetches
// raw football data; betting odds are generated by the use case layer, so we
// never spend the scarce free-tier request budget on the /odds endpoint.
type APISportsProvider struct {
	baseURL string
	apiKey  string
	season  string
	http    *http.Client
}

// NewAPISportsProvider builds a provider for the given credentials.
func NewAPISportsProvider(baseURL, apiKey, season string) *APISportsProvider {
	return &APISportsProvider{
		baseURL: baseURL,
		apiKey:  apiKey,
		season:  season,
		http:    &http.Client{Timeout: 10 * time.Second},
	}
}

// Leagues returns the competitions the app offers. We keep this static (the
// FIFA World Cup, league id 1) to avoid spending request budget on metadata.
func (p *APISportsProvider) Leagues(ctx context.Context) ([]domain.League, error) {
	return []domain.League{{
		ID:      worldCupID,
		Name:    "FIFA World Cup",
		Country: "World",
		Logo:    "https://media.api-sports.io/football/leagues/1.png",
	}}, nil
}

func (p *APISportsProvider) get(ctx context.Context, path string, q url.Values, out any) error {
	u := p.baseURL + path + "?" + q.Encode()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u, nil)
	if err != nil {
		return err
	}
	req.Header.Set("x-apisports-key", p.apiKey)
	resp, err := p.http.Do(req)
	if err != nil {
		return fmt.Errorf("api-football request failed: %w", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("api-football returned status %d", resp.StatusCode)
	}
	return json.NewDecoder(resp.Body).Decode(out)
}

// ---- Fixtures ----

type fixturesResponse struct {
	Response []struct {
		Fixture struct {
			ID     int       `json:"id"`
			Date   time.Time `json:"date"`
			Status struct {
				Short   string `json:"short"`
				Elapsed *int   `json:"elapsed"`
			} `json:"status"`
		} `json:"fixture"`
		Teams struct {
			Home apiTeam `json:"home"`
			Away apiTeam `json:"away"`
		} `json:"teams"`
		Goals struct {
			Home *int `json:"home"`
			Away *int `json:"away"`
		} `json:"goals"`
	} `json:"response"`
}

type apiTeam struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
	Logo string `json:"logo"`
}

func (t apiTeam) toDomain() domain.Team {
	return domain.Team{ID: strconv.Itoa(t.ID), Name: t.Name, Logo: t.Logo}
}

func (p *APISportsProvider) Matches(ctx context.Context, leagueID string) ([]domain.Match, error) {
	q := url.Values{}
	q.Set("league", leagueID)
	q.Set("season", p.season)

	var body fixturesResponse
	if err := p.get(ctx, "/fixtures", q, &body); err != nil {
		return nil, err
	}

	matches := make([]domain.Match, 0, len(body.Response))
	for _, f := range body.Response {
		status := mapStatus(f.Fixture.Status.Short)
		m := domain.Match{
			ID:       strconv.Itoa(f.Fixture.ID),
			LeagueID: leagueID,
			Date:     f.Fixture.Date,
			Status:   status,
			HomeTeam: f.Teams.Home.toDomain(),
			AwayTeam: f.Teams.Away.toDomain(),
			Time:     matchClock(f.Fixture.Status.Short, f.Fixture.Status.Elapsed),
		}
		if f.Goals.Home != nil && f.Goals.Away != nil {
			m.Score = &domain.Score{Home: *f.Goals.Home, Away: *f.Goals.Away}
		}
		matches = append(matches, m)
	}
	return matches, nil
}

// ---- Standings ----

type standingsResponse struct {
	Response []struct {
		League struct {
			Standings [][]struct {
				Rank int     `json:"rank"`
				Team apiTeam `json:"team"`
				All  struct {
					Played int `json:"played"`
					Win    int `json:"win"`
					Draw   int `json:"draw"`
					Lose   int `json:"lose"`
				} `json:"all"`
				Points    int `json:"points"`
				GoalsDiff int `json:"goalsDiff"`
			} `json:"standings"`
		} `json:"league"`
	} `json:"response"`
}

func (p *APISportsProvider) Standings(ctx context.Context, leagueID string) ([]domain.Standing, error) {
	q := url.Values{}
	q.Set("league", leagueID)
	q.Set("season", p.season)

	var body standingsResponse
	if err := p.get(ctx, "/standings", q, &body); err != nil {
		return nil, err
	}

	out := []domain.Standing{}
	for _, r := range body.Response {
		for _, group := range r.League.Standings {
			for _, s := range group {
				out = append(out, domain.Standing{
					Rank:           s.Rank,
					Team:           s.Team.toDomain(),
					Played:         s.All.Played,
					Win:            s.All.Win,
					Draw:           s.All.Draw,
					Loss:           s.All.Lose,
					Points:         s.Points,
					GoalDifference: s.GoalsDiff,
				})
			}
		}
	}
	return out, nil
}

// mapStatus translates api-football short status codes to our domain status.
func mapStatus(short string) domain.MatchStatus {
	switch short {
	case "NS", "TBD", "PST":
		return domain.StatusUpcoming
	case "1H", "HT", "2H", "ET", "BT", "P", "SUSP", "INT", "LIVE":
		return domain.StatusLive
	default: // FT, AET, PEN, CANC, ABD, AWD, WO, ...
		return domain.StatusFinished
	}
}

// matchClock produces the small time label shown on a match card.
func matchClock(short string, elapsed *int) string {
	switch short {
	case "HT":
		return "HT"
	case "FT", "AET", "PEN":
		return "FT"
	}
	if elapsed != nil {
		return strconv.Itoa(*elapsed) + "'"
	}
	return ""
}
